# Generated by Django 4.2.1 on 2023-07-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_image_alter_comment_body_alter_comment_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="products/product_cover",
                verbose_name="Product Image",
            ),
        ),
    ]
