# Generated by Django 4.2.1 on 2023-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="product/product_cover",
                verbose_name="Product Image",
            ),
        ),
    ]
