# Generated by Django 4.2.1 on 2023-07-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("other", "other"), ("dress", "dress"), ("pants", "pants")],
                max_length=6,
            ),
        ),
    ]
