# Generated by Django 4.2.1 on 2023-07-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_size_remove_product_category_productsize"),
    ]

    operations = [
        migrations.DeleteModel(name="ProductSize",),
        migrations.DeleteModel(name="Size",),
    ]
